/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foms;


import dao.ConnectionProvider;
import java.awt.Color;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import utility.MMPutility;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author marga
 */
public class ViewAttendance extends javax.swing.JFrame {

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        MMPutility.setImage(this, "images/abc1.jpg", 1101, 501);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4,4,4,4, Color.BLACK));
        
        FromDate.setDateFormatString("yyyy-MM-dd");
        ToDate.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        ToDate = new com.toedter.calendar.JDateChooser();
        FromDate = new com.toedter.calendar.JDateChooser();
        txtSearch = new javax.swing.JTextField();
        Presentlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        Absentlbl = new javax.swing.JLabel();
        CheckBoxContact = new javax.swing.JCheckBox();
        CheckBoxAddress = new javax.swing.JCheckBox();
        CheckBoxState = new javax.swing.JCheckBox();
        CheckBoxCountry = new javax.swing.JCheckBox();
        CheckBoxURID = new javax.swing.JCheckBox();
        ResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1101, 501));
        setMinimumSize(new java.awt.Dimension(1101, 501));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Attendance Track");

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setText("X");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(UserTable);

        ToDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ToDatePropertyChange(evt);
            }
        });

        FromDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FromDatePropertyChange(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        Presentlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Presentlbl.setText("Present");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("On / From");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("To");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Search");

        lblPresent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(0, 204, 0));
        lblPresent.setText("---------");

        lblAbsent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(204, 0, 0));
        lblAbsent.setText("---------");

        Absentlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Absentlbl.setText("Absent");

        CheckBoxContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxContact.setText("Contact");
        CheckBoxContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxContactItemStateChanged(evt);
            }
        });

        CheckBoxAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxAddress.setText("Address");
        CheckBoxAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxAddressItemStateChanged(evt);
            }
        });

        CheckBoxState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxState.setText("State");
        CheckBoxState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxStateItemStateChanged(evt);
            }
        });

        CheckBoxCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxCountry.setText("Country");
        CheckBoxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxCountryItemStateChanged(evt);
            }
        });

        CheckBoxURID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxURID.setText("Unique Reg ID");
        CheckBoxURID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxURIDItemStateChanged(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ResetButton.setText("Reset Filters");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnexit))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(409, 409, 409))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Absentlbl)
                            .addComponent(Presentlbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPresent)
                            .addComponent(lblAbsent)))
                    .addComponent(CheckBoxContact)
                    .addComponent(CheckBoxAddress)
                    .addComponent(CheckBoxState)
                    .addComponent(CheckBoxCountry)
                    .addComponent(CheckBoxURID)
                    .addComponent(ResetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnexit)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Presentlbl)
                            .addComponent(lblPresent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Absentlbl)
                            .addComponent(lblAbsent))
                        .addGap(54, 54, 54)
                        .addComponent(CheckBoxContact)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBoxAddress)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBoxState)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBoxCountry)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBoxURID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        
        txtSearch.setText("");
        FromDate.setDate(null);
        ToDate.setDate(null);
        CheckBoxContact.setSelected(false);
        CheckBoxAddress.setSelected(false);
        CheckBoxState.setSelected(false);
        CheckBoxCountry.setSelected(false);
        CheckBoxURID.setSelected(false);
        
        loadDataInTable();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void CheckBoxContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxContactItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxContactItemStateChanged

    private void CheckBoxAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxAddressItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxAddressItemStateChanged

    private void CheckBoxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxStateItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxStateItemStateChanged

    private void CheckBoxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxCountryItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxCountryItemStateChanged

    private void CheckBoxURIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxURIDItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxURIDItemStateChanged

    private void FromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FromDatePropertyChange
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_FromDatePropertyChange

    private void ToDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ToDatePropertyChange
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_ToDatePropertyChange

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absentlbl;
    private javax.swing.JCheckBox CheckBoxAddress;
    private javax.swing.JCheckBox CheckBoxContact;
    private javax.swing.JCheckBox CheckBoxCountry;
    private javax.swing.JCheckBox CheckBoxState;
    private javax.swing.JCheckBox CheckBoxURID;
    private com.toedter.calendar.JDateChooser FromDate;
    private javax.swing.JLabel Presentlbl;
    private javax.swing.JButton ResetButton;
    private com.toedter.calendar.JDateChooser ToDate;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {
        List<String> columns = new ArrayList<>(Arrays.asList(
                "ID", "Name", "Gender", "Email", "Date", "CheckIn", "CheckOut", "Work Duration"
        ));
        String searchText=txtSearch.getText().toString();
        Date fromDateFromCal=FromDate.getDate();
        LocalDate fromdate=null;
        if (fromDateFromCal != null) {
            fromdate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        Date toDateFromCal = ToDate.getDate();
        LocalDate toDate = null;
        if (toDateFromCal != null) {
            toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        Long daysBetween = null;
        if (fromdate != null && toDate != null) {
            daysBetween = countWeekdays(fromdate, toDate);
        }

        Boolean contactIncluded = CheckBoxContact.isSelected();
        Boolean addressIncluded = CheckBoxAddress.isSelected();
        Boolean stateIncluded = CheckBoxState.isSelected();
        Boolean countryIncluded = CheckBoxCountry.isSelected();
        Boolean uniqueRegIdIncluded = CheckBoxURID.isSelected();

        String sqlQuery = "SELECT ud.uid, ud.name,ud.gender, ud.email, ua.date, ua.checkin, ua.checkout, ua.workduration";
        if (contactIncluded) {
            columns.add("Contact");
            sqlQuery += ", ud.contact";
        }

        if (addressIncluded) {
            columns.add("Address");
            sqlQuery += ", ud.address";
        }

        if (stateIncluded) {
            columns.add("State");
            sqlQuery += ", ud.state";
        }

        if (countryIncluded) {
            columns.add("Country");
            sqlQuery += ", ud.country";
        }

        if (uniqueRegIdIncluded) {
            columns.add("Unique Reg Id");
            sqlQuery += ", ud.uniqueregid";
        }

        sqlQuery += " FROM userdetails ud INNER JOIN userattendance ua ON ud.uid = ua.userid ";
        if (searchText != null) {
            sqlQuery += " where (ud.name like '%" + searchText + "%' or ud.email like '%" + searchText + "%')";
            if (fromdate != null && toDate != null) {
                sqlQuery += " AND ua.date BETWEEN '" + fromdate + "' AND '" + toDate + "'";
            } else if (fromdate != null) {
                sqlQuery += " and ua.date = '" + fromdate + "'";
            }
        } else {
            if (fromdate != null && toDate != null) {
                sqlQuery += " where ua.date BETWEEN '" + fromdate + "' AND '" + toDate + "'";
            } else if (fromdate != null) {
                sqlQuery += " where ua.date = '" + fromdate + "'";
            }
        }

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        UserTable.setModel(model);

        try {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery(sqlQuery);
            Long presentCount = 0l;
            Long absentCount = 0l;
            Set<String> emailList = new HashSet<>();
            while (rs.next()) {
                List<Object> row = new ArrayList<>();
                row.add(rs.getString("uid"));
                row.add(rs.getString("name"));
                row.add(rs.getString("gender"));
                row.add(rs.getString("email"));
                emailList.add(rs.getString("email"));
                row.add(rs.getString("date"));
                row.add(rs.getString("checkin"));
                row.add(rs.getString("checkout"));
                row.add(rs.getString("workduration"));

                if (contactIncluded) {
                    row.add(rs.getString("contact"));
                }
                if (addressIncluded) {
                    row.add(rs.getString("address"));
                }
                if (stateIncluded) {
                    row.add(rs.getString("state"));
                }
                if (countryIncluded) {
                    row.add(rs.getString("country"));
                }
                if (uniqueRegIdIncluded) {
                    row.add(rs.getString("uniqueregid"));
                }

                if (rs.getString("checkout") == null) {
                    absentCount++;
                } else {
                    presentCount++;
                }
                model.addRow(row.toArray());
            }

            if (emailList.size() == 1) {
                lblPresent.setVisible(true);
                lblAbsent.setVisible(true);
                Presentlbl.setVisible(true);
                Absentlbl.setVisible(true);
                lblPresent.setText(presentCount.toString());
                if (daysBetween != null && daysBetween > 0) {
                    absentCount = daysBetween - presentCount;
                }
                lblAbsent.setText(absentCount.toString());
            } else {
                lblPresent.setVisible(false);
                lblAbsent.setVisible(false);
                Presentlbl.setVisible(false);
                Absentlbl.setVisible(false);
            }

        } catch (Exception ex) {
            ex.printStackTrace(); 
            JOptionPane.showMessageDialog(null, "Something went wrong.");
        }
    } // <-- Make sure this closing brace is present and correctly placed

    private Long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while (date.isBefore(end) || date.equals(end)) {
            if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }


}

